; Arena Breakout — XC GAMEUSER MOD
; Path: /sdcard/Android/data/com.proximabeta.mf.u/files/UE4Game/MaoXian/MaoXian/Saved/Config/Android/GameUserSettings.ini

[/Script/Engine.GameUserSettings]
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=720
ResolutionSizeY=1600
LastUserConfirmedResolutionSizeX=720
LastUserConfirmedResolutionSizeY=1600
WindowPosX=-1
WindowPosY=-1
FullscreenMode=0
LastConfirmedFullscreenMode=0
PreferredFullscreenMode=0
Version=5
AudioQualityLevel=0
LastConfirmedAudioQualityLevel=0
FrameRateLimit=120.000000
DesiredScreenWidth=720
DesiredScreenHeight=1600
LastUserConfirmedDesiredScreenWidth=720
LastUserConfirmedDesiredScreenHeight=1600
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=-1.000000
LastGPUBenchmarkResult=-1.000000
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000

ScalabilityQuality.ResolutionQuality=85
ScalabilityQuality.ViewDistanceQuality=2
ScalabilityQuality.AntiAliasingQuality=0
ScalabilityQuality.ShadowQuality=0
ScalabilityQuality.PostProcessQuality=0
ScalabilityQuality.TextureQuality=2
ScalabilityQuality.EffectsQuality=0
ScalabilityQuality.FoliageQuality=0
ScalabilityQuality.ShadingQuality=1
